#!/bin/sh

# A somewhat kludgy way of passing a value to the postinstall script, using launchctl's setenv/getenv/unsetenv commands.
open /Applications/HelloApp.app --args --UID $(launchctl getenv HELLO_APP_ARG)
